import { Language, Currency } from './types';

export const CATEGORIES = {
  income: ['Salário', 'Freelance', 'Investimentos', 'Presente', 'Outros'],
  expense: ['Alimentação', 'Moradia', 'Transporte', 'Lazer', 'Saúde', 'Educação', 'Compras', 'Outros']
};

export const TRANSLATIONS = {
  pt: {
    dashboard: 'Painel',
    transactions: 'Transações',
    reports: 'Relatórios',
    settings: 'Configurações',
    aiAdvisor: 'DinDin AI',
    balance: 'Saldo Atual',
    income: 'Receitas',
    expense: 'Despesas',
    addTransaction: 'Nova Transação',
    description: 'Descrição',
    amount: 'Valor',
    category: 'Categoria',
    date: 'Data',
    recurring: 'Recorrente',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    language: 'Idioma',
    currency: 'Moeda',
    proVersion: 'Versão PRO',
    backup: 'Backup na Nuvem (Drive/Dropbox)',
    export: 'Exportar CSV',
    security: 'Segurança',
    enablePin: 'Proteger com PIN',
    setPin: 'Definir PIN (4 dígitos)',
    enterPin: 'Digite seu PIN',
    unlock: 'Desbloquear',
    welcome: 'Bem-vindo ao DinDin',
    aiAnalysis: 'Análise Inteligente',
    aiPrompt: 'O que você quer saber sobre suas finanças?',
    getAdvice: 'Obter Análise',
    loading: 'Carregando...',
    noTransactions: 'Nenhuma transação registrada.',
    proFeature: 'Funcionalidade PRO',
    upgradeToPro: 'Atualize para PRO',
    total: 'Total',
    type: 'Tipo',
    search: 'Buscar...'
  },
  en: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    reports: 'Reports',
    settings: 'Settings',
    aiAdvisor: 'DinDin AI',
    balance: 'Current Balance',
    income: 'Income',
    expense: 'Expenses',
    addTransaction: 'New Transaction',
    description: 'Description',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    recurring: 'Recurring',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    language: 'Language',
    currency: 'Currency',
    proVersion: 'PRO Version',
    backup: 'Cloud Backup (Drive/Dropbox)',
    export: 'Export CSV',
    security: 'Security',
    enablePin: 'Protect with PIN',
    setPin: 'Set PIN (4 digits)',
    enterPin: 'Enter your PIN',
    unlock: 'Unlock',
    welcome: 'Welcome to DinDin',
    aiAnalysis: 'Smart Analysis',
    aiPrompt: 'What do you want to know about your finances?',
    getAdvice: 'Get Advice',
    loading: 'Loading...',
    noTransactions: 'No transactions recorded.',
    proFeature: 'PRO Feature',
    upgradeToPro: 'Upgrade to PRO',
    total: 'Total',
    type: 'Type',
    search: 'Search...'
  },
  es: {
    dashboard: 'Panel',
    transactions: 'Transacciones',
    reports: 'Informes',
    settings: 'Ajustes',
    aiAdvisor: 'DinDin IA',
    balance: 'Saldo Actual',
    income: 'Ingresos',
    expense: 'Gastos',
    addTransaction: 'Nueva Transacción',
    description: 'Descripción',
    amount: 'Monto',
    category: 'Categoría',
    date: 'Fecha',
    recurring: 'Recurrente',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    language: 'Idioma',
    currency: 'Moneda',
    proVersion: 'Versión PRO',
    backup: 'Copia de seguridad (Drive/Dropbox)',
    export: 'Exportar CSV',
    security: 'Seguridad',
    enablePin: 'Proteger con PIN',
    setPin: 'Establecer PIN (4 dígitos)',
    enterPin: 'Ingrese su PIN',
    unlock: 'Desbloquear',
    welcome: 'Bienvenido a DinDin',
    aiAnalysis: 'Análisis Inteligente',
    aiPrompt: '¿Qué quieres saber sobre tus finanzas?',
    getAdvice: 'Obtener Consejo',
    loading: 'Cargando...',
    noTransactions: 'No hay transacciones registradas.',
    proFeature: 'Función PRO',
    upgradeToPro: 'Actualizar a PRO',
    total: 'Total',
    type: 'Tipo',
    search: 'Buscar...'
  },
  fr: {
    dashboard: 'Tableau de bord',
    transactions: 'Transactions',
    reports: 'Rapports',
    settings: 'Paramètres',
    aiAdvisor: 'DinDin IA',
    balance: 'Solde Actuel',
    income: 'Revenus',
    expense: 'Dépenses',
    addTransaction: 'Nouvelle Transaction',
    description: 'Description',
    amount: 'Montant',
    category: 'Catégorie',
    date: 'Date',
    recurring: 'Récurrent',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    language: 'Langue',
    currency: 'Devise',
    proVersion: 'Version PRO',
    backup: 'Sauvegarde Cloud (Drive/Dropbox)',
    export: 'Exporter CSV',
    security: 'Sécurité',
    enablePin: 'Protéger par PIN',
    setPin: 'Définir PIN (4 chiffres)',
    enterPin: 'Entrez votre PIN',
    unlock: 'Déverrouiller',
    welcome: 'Bienvenue sur DinDin',
    aiAnalysis: 'Analyse Intelligente',
    aiPrompt: 'Que voulez-vous savoir sur vos finances ?',
    getAdvice: 'Obtenir des conseils',
    loading: 'Chargement...',
    noTransactions: 'Aucune transaction enregistrée.',
    proFeature: 'Fonctionnalité PRO',
    upgradeToPro: 'Passer à PRO',
    total: 'Total',
    type: 'Type',
    search: 'Chercher...'
  }
};

export const CURRENCY_SYMBOLS: Record<Currency, string> = {
  BRL: 'R$',
  USD: '$',
  EUR: '€'
};

export const DEFAULT_SETTINGS = {
  language: 'pt' as Language,
  currency: 'BRL' as Currency,
  isPro: false,
  hasPasswordProtection: false,
  passwordPin: '',
  theme: 'light' as const
};
