import { Language, Currency, CategoryItem } from './types';

// Default Data for Initialization
export const DEFAULT_CATEGORIES_LIST: CategoryItem[] = [
  // Income
  { id: 'inc_1', name: 'Salário', type: 'income', icon: 'Briefcase', color: 'bg-emerald-500' },
  { id: 'inc_2', name: 'Freelance', type: 'income', icon: 'Laptop', color: 'bg-blue-500' },
  { id: 'inc_3', name: 'Investimentos', type: 'income', icon: 'TrendingUp', color: 'bg-green-500' },
  { id: 'inc_4', name: 'Presente', type: 'income', icon: 'Gift', color: 'bg-pink-500' },
  // Expense
  { id: 'exp_1', name: 'Alimentação', type: 'expense', icon: 'Utensils', color: 'bg-orange-500' },
  { id: 'exp_2', name: 'Moradia', type: 'expense', icon: 'Home', color: 'bg-indigo-500' },
  { id: 'exp_3', name: 'Transporte', type: 'expense', icon: 'Car', color: 'bg-blue-600' },
  { id: 'exp_4', name: 'Lazer', type: 'expense', icon: 'Smile', color: 'bg-purple-500' },
  { id: 'exp_5', name: 'Saúde', type: 'expense', icon: 'Heart', color: 'bg-red-500' },
  { id: 'exp_6', name: 'Educação', type: 'expense', icon: 'GraduationCap', color: 'bg-yellow-500' },
  { id: 'exp_7', name: 'Compras', type: 'expense', icon: 'ShoppingBag', color: 'bg-teal-500' },
  { id: 'exp_8', name: 'Outros', type: 'expense', icon: 'MoreHorizontal', color: 'bg-gray-500' }
];

export const AVAILABLE_ICONS = [
  'Briefcase', 'Laptop', 'TrendingUp', 'Gift', 'Utensils', 'Home', 'Car', 
  'Smile', 'Heart', 'GraduationCap', 'ShoppingBag', 'MoreHorizontal',
  'Zap', 'Wifi', 'Smartphone', 'Coffee', 'Music', 'Plane', 'Gamepad', 
  'Dumbbell', 'Stethoscope', 'Book', 'Hammer', 'Dog'
];

export const AVAILABLE_COLORS = [
  'bg-slate-500', 'bg-red-500', 'bg-orange-500', 'bg-amber-500', 
  'bg-yellow-500', 'bg-lime-500', 'bg-green-500', 'bg-emerald-500', 
  'bg-teal-500', 'bg-cyan-500', 'bg-sky-500', 'bg-blue-500', 
  'bg-indigo-500', 'bg-violet-500', 'bg-purple-500', 'bg-fuchsia-500', 
  'bg-pink-500', 'bg-rose-500'
];

// Kept for backward compatibility if needed, but UI uses dynamic list now
export const CATEGORIES = {
  income: DEFAULT_CATEGORIES_LIST.filter(c => c.type === 'income').map(c => c.name),
  expense: DEFAULT_CATEGORIES_LIST.filter(c => c.type === 'expense').map(c => c.name)
};

export const TRANSLATIONS = {
  pt: {
    dashboard: 'Painel',
    budget: 'Orçamento',
    categories: 'Categorias',
    reports: 'Relatórios',
    settings: 'Configurações',
    aiAdvisor: 'DinDin AI',
    balance: 'Saldo',
    income: 'Receitas',
    expense: 'Despesas',
    addTransaction: 'Nova Transação',
    description: 'Descrição',
    amount: 'Valor',
    category: 'Categoria',
    date: 'Data',
    recurring: 'Recorrente',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    language: 'Idioma',
    currency: 'Moeda',
    theme: 'Tema',
    lightMode: 'Modo Claro',
    darkMode: 'Modo Escuro',
    proVersion: 'Versão PRO',
    backup: 'Backup na Nuvem (Drive/Dropbox)',
    export: 'Exportar CSV',
    security: 'Segurança',
    enablePin: 'Proteger com PIN',
    setPin: 'Definir PIN (4 dígitos)',
    enterPin: 'Digite seu PIN',
    unlock: 'Desbloquear',
    welcome: 'Bem-vindo ao DinDin',
    aiAnalysis: 'Análise Inteligente',
    aiPrompt: 'O que você quer saber sobre suas finanças?',
    getAdvice: 'Obter Análise',
    loading: 'Carregando...',
    noTransactions: 'Nenhuma transação registrada.',
    proFeature: 'Funcionalidade PRO',
    upgradeToPro: 'Atualize para PRO',
    total: 'Total',
    type: 'Tipo',
    search: 'Buscar...',
    addBudget: 'Novo Orçamento',
    limit: 'Limite',
    spent: 'Gasto',
    remaining: 'Restante',
    overBudget: 'Orçamento Estourado!',
    budgetAlert: 'Cuidado! Você usou',
    ofBudget: 'do seu orçamento.',
    noBudgets: 'Nenhum orçamento definido.',
    addCategory: 'Nova Categoria',
    editCategory: 'Editar Categoria',
    categoryName: 'Nome da Categoria',
    icon: 'Ícone',
    color: 'Cor',
    both: 'Ambos',
    thisMonth: 'Este Mês',
    lastMonth: 'Mês Passado',
    thisYear: 'Este Ano',
    custom: 'Período',
    byPeriod: 'Por Período',
    financialSummary: 'Resumo Financeiro',
    all: 'Todos',
    allCategories: 'Todas Categorias',
    selectPeriod: 'Selecionar Período',
    startDate: 'Data Inicial',
    endDate: 'Data Final',
    filters: 'Filtros',
    backupSettings: 'Backup & Dados',
    createBackup: 'Criar Backup (JSON)',
    restoreBackup: 'Restaurar Backup (JSON)',
    lastBackup: 'Último backup:',
    backupCreated: 'Backup criado com sucesso',
    backupRestored: 'Salvo com sucesso',
    never: 'Nunca'
  },
  en: {
    dashboard: 'Dashboard',
    budget: 'Budget',
    categories: 'Categories',
    reports: 'Reports',
    settings: 'Settings',
    aiAdvisor: 'DinDin AI',
    balance: 'Balance',
    income: 'Income',
    expense: 'Expenses',
    addTransaction: 'New Transaction',
    description: 'Description',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    recurring: 'Recurring',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    proVersion: 'PRO Version',
    backup: 'Cloud Backup (Drive/Dropbox)',
    export: 'Export CSV',
    security: 'Security',
    enablePin: 'Protect with PIN',
    setPin: 'Set PIN (4 digits)',
    enterPin: 'Enter your PIN',
    unlock: 'Unlock',
    welcome: 'Welcome to DinDin',
    aiAnalysis: 'Smart Analysis',
    aiPrompt: 'What do you want to know about your finances?',
    getAdvice: 'Get Advice',
    loading: 'Loading...',
    noTransactions: 'No transactions recorded.',
    proFeature: 'PRO Feature',
    upgradeToPro: 'Upgrade to PRO',
    total: 'Total',
    type: 'Type',
    search: 'Search...',
    addBudget: 'New Budget',
    limit: 'Limit',
    spent: 'Spent',
    remaining: 'Remaining',
    overBudget: 'Over Budget!',
    budgetAlert: 'Warning! You used',
    ofBudget: 'of your budget.',
    noBudgets: 'No budgets defined.',
    addCategory: 'New Category',
    editCategory: 'Edit Category',
    categoryName: 'Category Name',
    icon: 'Icon',
    color: 'Color',
    both: 'Both',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    thisYear: 'This Year',
    custom: 'Custom',
    byPeriod: 'By Period',
    financialSummary: 'Financial Summary',
    all: 'All',
    allCategories: 'All Categories',
    selectPeriod: 'Select Period',
    startDate: 'Start Date',
    endDate: 'End Date',
    filters: 'Filters',
    backupSettings: 'Backup & Data',
    createBackup: 'Create Backup (JSON)',
    restoreBackup: 'Restore Backup (JSON)',
    lastBackup: 'Last backup:',
    backupCreated: 'Backup created successfully',
    backupRestored: 'Saved successfully',
    never: 'Never'
  },
  es: {
    dashboard: 'Panel',
    budget: 'Presupuesto',
    categories: 'Categorías',
    reports: 'Informes',
    settings: 'Ajustes',
    aiAdvisor: 'DinDin IA',
    balance: 'Saldo',
    income: 'Ingresos',
    expense: 'Gastos',
    addTransaction: 'Nueva Transacción',
    description: 'Descripción',
    amount: 'Monto',
    category: 'Categoría',
    date: 'Fecha',
    recurring: 'Recurrente',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    language: 'Idioma',
    currency: 'Moneda',
    theme: 'Tema',
    lightMode: 'Modo Claro',
    darkMode: 'Modo Oscuro',
    proVersion: 'Versión PRO',
    backup: 'Copia de seguridad (Drive/Dropbox)',
    export: 'Exportar CSV',
    security: 'Seguridad',
    enablePin: 'Proteger con PIN',
    setPin: 'Establecer PIN (4 dígitos)',
    enterPin: 'Ingrese su PIN',
    unlock: 'Desbloquear',
    welcome: 'Bienvenido a DinDin',
    aiAnalysis: 'Análisis Inteligente',
    aiPrompt: '¿Qué quieres saber sobre tus finanzas?',
    getAdvice: 'Obtener Consejo',
    loading: 'Cargando...',
    noTransactions: 'No hay transacciones registradas.',
    proFeature: 'Función PRO',
    upgradeToPro: 'Actualizar a PRO',
    total: 'Total',
    type: 'Tipo',
    search: 'Buscar...',
    addBudget: 'Nuevo Presupuesto',
    limit: 'Límite',
    spent: 'Gastado',
    remaining: 'Restante',
    overBudget: '¡Presupuesto Excedido!',
    budgetAlert: '¡Cuidado! Has usado',
    ofBudget: 'de tu presupuesto.',
    noBudgets: 'No hay presupuestos definidos.',
    addCategory: 'Nueva Categoría',
    editCategory: 'Editar Categoría',
    categoryName: 'Nombre de la Categoría',
    icon: 'Icono',
    color: 'Color',
    both: 'Ambos',
    thisMonth: 'Este Mes',
    lastMonth: 'Mes Pasado',
    thisYear: 'Este Año',
    custom: 'Personalizado',
    byPeriod: 'Por Período',
    financialSummary: 'Resumen Financiero',
    all: 'Todos',
    allCategories: 'Todas Categorías',
    selectPeriod: 'Seleccionar Período',
    startDate: 'Fecha Inicio',
    endDate: 'Fecha Fin',
    filters: 'Filtros',
    backupSettings: 'Respaldo y Datos',
    createBackup: 'Crear Respaldo (JSON)',
    restoreBackup: 'Restaurar Respaldo (JSON)',
    lastBackup: 'Último respaldo:',
    backupCreated: 'Respaldo creado con éxito',
    backupRestored: 'Guardado con éxito',
    never: 'Nunca'
  },
  fr: {
    dashboard: 'Tableau de bord',
    budget: 'Budget',
    categories: 'Catégories',
    reports: 'Rapports',
    settings: 'Paramètres',
    aiAdvisor: 'DinDin IA',
    balance: 'Solde',
    income: 'Revenus',
    expense: 'Dépenses',
    addTransaction: 'Nouvelle Transaction',
    description: 'Description',
    amount: 'Montant',
    category: 'Catégorie',
    date: 'Date',
    recurring: 'Récurrent',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    language: 'Langue',
    currency: 'Devise',
    theme: 'Thème',
    lightMode: 'Mode Clair',
    darkMode: 'Mode Sombre',
    proVersion: 'Version PRO',
    backup: 'Sauvegarde Cloud (Drive/Dropbox)',
    export: 'Exporter CSV',
    security: 'Sécurité',
    enablePin: 'Protéger par PIN',
    setPin: 'Définir PIN (4 chiffres)',
    enterPin: 'Entrez votre PIN',
    unlock: 'Déverrouiller',
    welcome: 'Bienvenue sur DinDin',
    aiAnalysis: 'Analyse Intelligente',
    aiPrompt: 'Que voulez-vous savoir sur vos finances ?',
    getAdvice: 'Obtenir des conseils',
    loading: 'Chargement...',
    noTransactions: 'Aucune transaction enregistrée.',
    proFeature: 'Fonctionnalité PRO',
    upgradeToPro: 'Passer à PRO',
    total: 'Total',
    type: 'Type',
    search: 'Chercher...',
    addBudget: 'Nouveau Budget',
    limit: 'Limite',
    spent: 'Dépensé',
    remaining: 'Restant',
    overBudget: 'Budget Dépassé !',
    budgetAlert: 'Attention ! Vous avez utilisé',
    ofBudget: 'de votre budget.',
    noBudgets: 'Aucun budget défini.',
    addCategory: 'Nouvelle Catégorie',
    editCategory: 'Modifier Catégorie',
    categoryName: 'Nom de la Catégorie',
    icon: 'Icône',
    color: 'Couleur',
    both: 'Les deux',
    thisMonth: 'Ce Mois',
    lastMonth: 'Mois Dernier',
    thisYear: 'Cette Année',
    custom: 'Personnalisé',
    byPeriod: 'Par Période',
    financialSummary: 'Résumé Financier',
    all: 'Tous',
    allCategories: 'Toutes Catégories',
    selectPeriod: 'Choisir Période',
    startDate: 'Date Début',
    endDate: 'Date Fin',
    filters: 'Filtres',
    backupSettings: 'Sauvegarde et Données',
    createBackup: 'Créer Sauvegarde (JSON)',
    restoreBackup: 'Restaurer Sauvegarde (JSON)',
    lastBackup: 'Dernière sauvegarde :',
    backupCreated: 'Sauvegarde créée avec succès',
    backupRestored: 'Enregistré avec succès',
    never: 'Jamais'
  }
};

export const CURRENCY_SYMBOLS: Record<Currency, string> = {
  BRL: 'R$',
  USD: '$',
  EUR: '€'
};

export const DEFAULT_SETTINGS = {
  language: 'pt' as Language,
  currency: 'BRL' as Currency,
  isPro: false,
  hasPasswordProtection: false,
  passwordPin: '',
  theme: 'light' as const
};